server:
  port: 9000
  context-path: /

spring:
  application:
    name: codemake
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # JDBC
  datasource:
    url: jdbc:mysql://47.104.189.214:3306/shouhou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: abc321@JG
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# @{link} https://github.com/abel533
#Mybatis
mybatis:
  type-aliases-package: com.simple.domain.po
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    use-generated-keys: true
    default-fetch-size: 100

logging:
  level:
    tk.mybatis: debug
    com.simple.mapper: debug
